# Generated by Django 3.2.6 on 2021-11-12 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20211111_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 1, 30, 31, 978273, tzinfo=utc)),
        ),
    ]
