# Generated by Django 3.2.6 on 2021-11-12 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 1, 32, 19, 725926, tzinfo=utc)),
        ),
    ]
