# Generated by Django 3.2.6 on 2021-12-10 23:01

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20211209_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='_network_user_follows_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 23, 0, 59, 493566, tzinfo=utc)),
        ),
    ]
