# Generated by Django 3.2.6 on 2021-12-11 00:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20211210_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 0, 24, 47, 184377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
    ]
