# Generated by Django 3.1.7 on 2021-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210811_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
