# Generated by Django 3.2.6 on 2021-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210916_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='state',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
